// source: common/contract.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.common.CertManageFunction', null, global);
goog.exportSymbol('proto.common.ConfigFunction', null, global);
goog.exportSymbol('proto.common.ContractId', null, global);
goog.exportSymbol('proto.common.ContractInfo', null, global);
goog.exportSymbol('proto.common.ContractName', null, global);
goog.exportSymbol('proto.common.ContractTransaction', null, global);
goog.exportSymbol('proto.common.ManageUserContractFunction', null, global);
goog.exportSymbol('proto.common.MultiSignFunction', null, global);
goog.exportSymbol('proto.common.QueryFunction', null, global);
goog.exportSymbol('proto.common.RuntimeType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.common.ContractId = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.common.ContractId, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.common.ContractId.displayName = 'proto.common.ContractId';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.common.ContractInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.common.ContractInfo.repeatedFields_, null);
};
goog.inherits(proto.common.ContractInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.common.ContractInfo.displayName = 'proto.common.ContractInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.common.ContractTransaction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.common.ContractTransaction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.common.ContractTransaction.displayName = 'proto.common.ContractTransaction';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.common.ContractId.prototype.toObject = function(opt_includeInstance) {
  return proto.common.ContractId.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.common.ContractId} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.common.ContractId.toObject = function(includeInstance, msg) {
  var f, obj = {
    contractName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    contractVersion: jspb.Message.getFieldWithDefault(msg, 2, ""),
    runtimeType: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.common.ContractId}
 */
proto.common.ContractId.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.common.ContractId;
  return proto.common.ContractId.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.common.ContractId} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.common.ContractId}
 */
proto.common.ContractId.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setContractName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setContractVersion(value);
      break;
    case 3:
      var value = /** @type {!proto.common.RuntimeType} */ (reader.readEnum());
      msg.setRuntimeType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.common.ContractId.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.common.ContractId.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.common.ContractId} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.common.ContractId.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContractName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getContractVersion();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRuntimeType();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional string contract_name = 1;
 * @return {string}
 */
proto.common.ContractId.prototype.getContractName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.common.ContractId} returns this
 */
proto.common.ContractId.prototype.setContractName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string contract_version = 2;
 * @return {string}
 */
proto.common.ContractId.prototype.getContractVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.common.ContractId} returns this
 */
proto.common.ContractId.prototype.setContractVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional RuntimeType runtime_type = 3;
 * @return {!proto.common.RuntimeType}
 */
proto.common.ContractId.prototype.getRuntimeType = function() {
  return /** @type {!proto.common.RuntimeType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.common.RuntimeType} value
 * @return {!proto.common.ContractId} returns this
 */
proto.common.ContractId.prototype.setRuntimeType = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.common.ContractInfo.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.common.ContractInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.common.ContractInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.common.ContractInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.common.ContractInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    contractTransactionList: jspb.Message.toObjectList(msg.getContractTransactionList(),
    proto.common.ContractTransaction.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.common.ContractInfo}
 */
proto.common.ContractInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.common.ContractInfo;
  return proto.common.ContractInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.common.ContractInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.common.ContractInfo}
 */
proto.common.ContractInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.common.ContractTransaction;
      reader.readMessage(value,proto.common.ContractTransaction.deserializeBinaryFromReader);
      msg.addContractTransaction(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.common.ContractInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.common.ContractInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.common.ContractInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.common.ContractInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContractTransactionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.common.ContractTransaction.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ContractTransaction contract_transaction = 1;
 * @return {!Array<!proto.common.ContractTransaction>}
 */
proto.common.ContractInfo.prototype.getContractTransactionList = function() {
  return /** @type{!Array<!proto.common.ContractTransaction>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.common.ContractTransaction, 1));
};


/**
 * @param {!Array<!proto.common.ContractTransaction>} value
 * @return {!proto.common.ContractInfo} returns this
*/
proto.common.ContractInfo.prototype.setContractTransactionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.common.ContractTransaction=} opt_value
 * @param {number=} opt_index
 * @return {!proto.common.ContractTransaction}
 */
proto.common.ContractInfo.prototype.addContractTransaction = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.common.ContractTransaction, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.common.ContractInfo} returns this
 */
proto.common.ContractInfo.prototype.clearContractTransactionList = function() {
  return this.setContractTransactionList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.common.ContractTransaction.prototype.toObject = function(opt_includeInstance) {
  return proto.common.ContractTransaction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.common.ContractTransaction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.common.ContractTransaction.toObject = function(includeInstance, msg) {
  var f, obj = {
    contractId: (f = msg.getContractId()) && proto.common.ContractId.toObject(includeInstance, f),
    txId: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.common.ContractTransaction}
 */
proto.common.ContractTransaction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.common.ContractTransaction;
  return proto.common.ContractTransaction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.common.ContractTransaction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.common.ContractTransaction}
 */
proto.common.ContractTransaction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.common.ContractId;
      reader.readMessage(value,proto.common.ContractId.deserializeBinaryFromReader);
      msg.setContractId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTxId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.common.ContractTransaction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.common.ContractTransaction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.common.ContractTransaction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.common.ContractTransaction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContractId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.common.ContractId.serializeBinaryToWriter
    );
  }
  f = message.getTxId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional ContractId contract_id = 1;
 * @return {?proto.common.ContractId}
 */
proto.common.ContractTransaction.prototype.getContractId = function() {
  return /** @type{?proto.common.ContractId} */ (
    jspb.Message.getWrapperField(this, proto.common.ContractId, 1));
};


/**
 * @param {?proto.common.ContractId|undefined} value
 * @return {!proto.common.ContractTransaction} returns this
*/
proto.common.ContractTransaction.prototype.setContractId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.common.ContractTransaction} returns this
 */
proto.common.ContractTransaction.prototype.clearContractId = function() {
  return this.setContractId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.common.ContractTransaction.prototype.hasContractId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string tx_id = 2;
 * @return {string}
 */
proto.common.ContractTransaction.prototype.getTxId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.common.ContractTransaction} returns this
 */
proto.common.ContractTransaction.prototype.setTxId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.common.ContractName = {
  SYSTEM_CONTRACT_CHAIN_CONFIG: 0,
  SYSTEM_CONTRACT_QUERY: 1,
  SYSTEM_CONTRACT_CERT_MANAGE: 2,
  SYSTEM_CONTRACT_GOVERNANCE: 3,
  SYSTEM_CONTRACT_MULTI_SIGN: 4
};

/**
 * @enum {number}
 */
proto.common.QueryFunction = {
  GET_BLOCK_BY_TX_ID: 0,
  GET_CONTRACT_INFO: 1,
  GET_TX_BY_TX_ID: 2,
  GET_BLOCK_BY_HEIGHT: 3,
  GET_CHAIN_INFO: 4,
  GET_LAST_CONFIG_BLOCK: 5,
  GET_BLOCK_BY_HASH: 6,
  GET_NODE_CHAIN_LIST: 7,
  GET_GOVERNANCE_CONTRACT: 8,
  GET_BLOCK_WITH_TXRWSETS_BY_HEIGHT: 9,
  GET_BLOCK_WITH_TXRWSETS_BY_HASH: 10,
  GET_LAST_BLOCK: 11
};

/**
 * @enum {number}
 */
proto.common.RuntimeType = {
  INVALID: 0,
  NATIVE: 1,
  WASMER: 2,
  WXVM: 3,
  GASM: 4,
  EVM: 5,
  DOCKER_GO: 6,
  DOCKER_JAVA: 7
};

/**
 * @enum {number}
 */
proto.common.ConfigFunction = {
  GET_CHAIN_CONFIG: 0,
  GET_CHAIN_CONFIG_AT: 1,
  CORE_UPDATE: 2,
  BLOCK_UPDATE: 3,
  TRUST_ROOT_ADD: 4,
  TRUST_ROOT_UPDATE: 5,
  TRUST_ROOT_DELETE: 6,
  NODE_ADDR_ADD: 7,
  NODE_ADDR_UPDATE: 8,
  NODE_ADDR_DELETE: 9,
  NODE_ORG_ADD: 10,
  NODE_ORG_UPDATE: 11,
  NODE_ORG_DELETE: 12,
  CONSENSUS_EXT_ADD: 13,
  CONSENSUS_EXT_UPDATE: 14,
  CONSENSUS_EXT_DELETE: 15,
  PERMISSION_ADD: 16,
  PERMISSION_UPDATE: 17,
  PERMISSION_DELETE: 18
};

/**
 * @enum {number}
 */
proto.common.CertManageFunction = {
  CERT_ADD: 0,
  CERTS_DELETE: 1,
  CERTS_QUERY: 2,
  CERTS_FREEZE: 3,
  CERTS_UNFREEZE: 4,
  CERTS_REVOKE: 5
};

/**
 * @enum {number}
 */
proto.common.MultiSignFunction = {
  REQ: 0,
  VOTE: 1,
  QUERY: 2
};

/**
 * @enum {number}
 */
proto.common.ManageUserContractFunction = {
  INIT_CONTRACT: 0,
  UPGRADE_CONTRACT: 1,
  FREEZE_CONTRACT: 2,
  UNFREEZE_CONTRACT: 3,
  REVOKE_CONTRACT: 4
};

goog.object.extend(exports, proto.common);
